export enum ErrorCode {
  DATA_NOT_FOUND = 'DATA_NOT_FOUND',
  EDGE_NOT_FOUND = 'EDGE_NOT_FOUND',
  DOCKER_LOGIN_FAILED = 'DOCKER_LOGIN_FAILED',
  DOCKER_RUN_FAILED = 'DOCKER_RUN_FAILED',
  DOCKER_INSPECT_FAILED = 'DOCKER_INSPECT_FAILED',
  DOCKER_LOGS_FAILED = 'DOCKER_LOGS_FAILED',
}
